# A very basic thing - add users
# Yet another line of comment

---
- hosts: all
  remote_user: ec2-user
  sudo: yes

  tasks:
    - name: Add new user
      user:
        name: marcindu
        state: present
        ssh_key_file: ~/.ssh/marcindu.qa.admin.pem
