# VPC for workspaces

---
- hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true

  vars:
    env: qa
  
  vars_files:
    - vars/var_workspaces.yml
  
    
  tasks:
    - name: VPC for Work Spaces
      cloudformation:
        state: present
        stack_name: WorkSpaces-VPC
        region: "{{ aws_region }}"
        template: cf/workspaces-aws-net.template
        template_parameters:
          AdminVpcId: "{{ admin_vpc_id }}"
          AdminVpcCidr: "{{ admin_vpc_cidr }}"
      register: ws_vpc
    
    
    - debug:
        msg: "{{ ws_vpc }}"
    
    
    - debug: msg={{ ws_vpc.stack_outputs.VpcId }}
    
    
    
    



