# VPC for workspaces

---
- hosts: localhost
  connection: local
  gather_facts: no
  any_errors_fatal: true

  vars:
    env: qa
    aws_region: eu-central-1
    ws_vpc:
      cidr_block: 192.168.16.0/20
      ws_tier_a:
        cidr_block: 192.168.17.0/24
      ws_tier_b:
        cidr_block: 192.168.25.0/24
      db_tier_a:
        cidr_block: 192.168.18.0/24
      db_tier_b:
        cidr_block: 192.168.26.0/24
  
  tasks:
    - name: VPC for Work Spaces
      ec2_vpc:
        state: present
        region: "{{ aws_region }}"
        cidr_block: "{{ ws_vpc.cidr_block }}"
        internet_gateway: yes
        resource_tags: { "Name": "ws-vpc", "Platform": "Networking" }
        
        subnets:
          - cidr: "{{ ws_vpc.ws_tier_a.cidr_block }}"
            az: "{{ aws_region }}a"
            resource_tags: { "Name": "ws-sub-ws-1a", "Platform": "Networking" }
          - cidr: "{{ ws_vpc.ws_tier_b.cidr_block }}"
            az: "{{ aws_region }}b"
            resource_tags: { "Name": "ws-sub-ws-1b", "Platform": "Networking" }
          - cidr: "{{ ws_vpc.db_tier_a.cidr_block }}"
            az: "{{ aws_region }}a"
            resource_tags: { "Name": "ws-sub-db-1a", "Platform": "Networking" }
          - cidr: "{{ ws_vpc.db_tier_b.cidr_block }}"
            az: "{{ aws_region }}b"
            resource_tags: { "Name": "ws-sub-db-1b", "Platform": "Networking" }
        
        route_tables:
          - subnets:
            - "{{ ws_vpc.ws_tier_a.cidr_block }}"
            - "{{ ws_vpc.ws_tier_b.cidr_block }}"
            routes:
              - dest: 0.0.0.0/0
                gw: igw

