# VPC for workspaces
# =================================================
# To create use command:
#  ~$ ansible-playbook ws-vpc.yml
#
# To remove the stack:
#  ~$ ansible-playbook ws-vpc.yml -e action=absent
#

---
- hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true


  vars_files:
    - vars/var_general.yml
    - vars/var_workspaces.yml
    
    
  tasks:
    - name: VPC for Work Spaces
      cloudformation:
        state: "{{ action | default('present') }}"
        stack_name: WorkSpaces-VPC
        region: "{{ aws_region }}"
        template: cf/workspaces-aws-net.template
        template_parameters:
          AdminVpcId: "{{ admin_vpc_id }}"
          AdminVpcCidr: "{{ admin_vpc_cidr }}"
      register: ws_vpc
    
    
    - debug:
        msg: "{{ ws_vpc }}"
    
    
    - debug: msg={{ ws_vpc.stack_outputs.VpcId }}
    
    
    
    



